# mamba create --platform osx-64 --name r_env1 r-terra r-exactextractr r-collapse r-ggpmisc r-qs r-tidymodels r-tidyverse r-showtext r-readxl r-fixest r-ncdf4 r-ggrepel r-ggtext r-slider r-kableExtra r-magick r-devtools r-qs r-lme4 r-gee r-hrbrthemes r-correlation r-cowplot r-ggdensity r-ggh4x r-ggside r-latex2exp r-ggdist r-performance r-MetBrewer r-countrycode r-openair
if (Sys.info()[1] == "Linux") {
  rm(list = ls())
  gc()
  options(future.globals.maxSize = 1e100)
  library(magrittr)
  library(terra)
  # remotes::install_github("rspatial/terra", configure.args = "--with-proj-lib=/opt/homebrew/Cellar/proj/9.5.0/lib/")
  library(raster, exclude = "select")
  library(tidyverse)
  library(tidymodels)
  library(data.table)
  library(lubridate)
  library(ggpmisc)
  library(collapse)
  library(scales)
  library(sf)
  sf_use_s2(F)
  library(readxl)
  library(exactextractr)
  library(fixest)
  library(Matrix)
  library(matrixStats, exclude = "count")
  library(ncdf4)
  library(splines)
  library(mgcv)
  library(furrr)
  library(qs)
  library(ggdist)
} else {
  rm(list = ls())
  gc()
  options(future.globals.maxSize = 1e100)
  library(magrittr)
  library(terra)
  # remotes::install_github("rspatial/terra", configure.args = "--with-proj-lib=/opt/homebrew/Cellar/proj/9.5.0/lib/")
  library(raster, exclude = "select")
  library(tidyverse)
  library(tidymodels)
  library(data.table)
  library(lubridate)
  library(ggpmisc)
  library(collapse)
  # if (Sys.info()[1] == "Windows") {
  #   sysfonts::font_add("Roboto Condensed", "D:/Software/R/R-4.2.3/library/hrbrthemes/fonts/roboto-condensed/RobotoCondensed-Regular.ttf")
  # } else {
  #   sysfonts::font_add("Roboto Condensed", "/Library/Frameworks/R.framework/Resources/library/hrbrthemes/fonts/roboto-condensed/RobotoCondensed-Regular.ttf")
  # }
  # showtext::showtext_auto()
  # showtext::showtext_opts(dpi = 300)
  terra::gdalCache(1e6)
  library(hrbrthemes)
  library(cowplot)
  library(ggh4x)
  library(scales)
  library(patchwork)
  library(sf)
  sf_use_s2(F)
  library(readxl)
  library(exactextractr)
  library(fixest)
  library(Matrix)
  library(matrixStats, exclude = "count")
  library(ncdf4)
  # library(splines)
  library(ggside)
  library(ggdensity)
  library(latex2exp)
  library(ggrepel)
  library(mgcv)
  # library(ggpointdensity)
  library(viridis)
  library(furrr)
  library(correlation)
  library(qs)
  # library(biscale)
  library(ggdist)
  library(ggtext)
  library(slider)
  library(kableExtra)
  library(magick)
  library(performance)
  library(usmap)
  library(ggalluvial)
  library(geosphere)
}
